import type { Metadata } from "next";
import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider"
import { Nav, MobileNav } from "@/components/nav";

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${jetbrainsMono.variable} font-mono antialiased min-h-screen w-full flex justify-center `}
      >
        <div className=" w-full md:max-w-5xl flex justify-center">
          <ThemeProvider
            attribute="class"
            defaultTheme="light"
            enableSystem
            disableTransitionOnChange
          >
            <div className="w-full h-full flex flex-col items-center gap-2">
              {/* Desktop Navigation - visible on medium screens and up */}
              <div className="w-full hidden md:block">
                <Nav />
              </div>
              
              {/* Mobile Navigation - visible on small screens only */}
              <div className="w-full md:hidden">
                <MobileNav />
              </div>
              
              {children}
            </div>
          </ThemeProvider>
        </div>
      </body>
    </html>
  );
}